In [1]:
import pandas as pd

df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
a = df.groupby("Sex")["Age"].mean()
a

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [3]:
b = df.groupby("Pclass")["PassengerId"].count()
b

Pclass
1    216
2    184
3    491
Name: PassengerId, dtype: int64

In [4]:
c = df.groupby("Pclass")["Fare"].agg(["mean", "max", "min"])
c

             mean       max  min
Pclass
1       84.154687  512.3292  0.0
2       20.662183   73.5000  0.0
3       13.675550   69.5500  0.0

In [5]:
d = df.groupby(["Sex", "Pclass"])["Fare"].mean()
d

Sex     Pclass
female  1         106.125798
        2          21.970121
        3          16.118810
male    1          67.226127
        2          19.741782
        3          12.661633
Name: Fare, dtype: float64

In [10]:
e = df.groupby(["Sex", "Pclass"])["Fare"].mean().reset_index()
e

      Sex  Pclass        Fare
0  female       1  106.125798
1  female       2   21.970121
2  female       3   16.118810
3    male       1   67.226127
4    male       2   19.741782
5    male       3   12.661633

In [12]:
f = df.groupby("Pclass")["Fare"].mean().sort_values(ascending=True)
f

Pclass
3    13.675550
2    20.662183
1    84.154687
Name: Fare, dtype: float64

In [14]:
g = df.groupby("Sex")["Fare"].mean().sort_values(ascending=True)
g

Sex
male      25.523893
female    44.479818
Name: Fare, dtype: float64